### PR TITLE
make the example programs optional

### PR DESCRIPTION
**Pull request by knight-of-ni**
as requested.
To include the example programs, one must call cmake with the OZ_EXAMPLES flag:
`cmake -DOZ_EXAMPLES=ON .`

### CODE REVIEW

**Comment by pliablepixels** [comment]
likely a bit of miscommunication here. What I meant was when you do cmake, it should also make examples, but the subsequent make install should not install these examples to /usr/local/bin. Right now unless you enable this flag, examples don't get built

**Comment by knight-of-ni** [comment]
I did understand what you asked, but I did not realize it would make a significant difference. 
After looking into it, It turned out that what you suggested was far more complicated than the way it is currently implemented. 

Currently, one can just run cmake a second time, this time with the OZ_EXAMPLES flag set, and cmake will build the executables, skipping over the libraries which have already been built. 

Can we focus on details like this later? I'd rather focus on major functionality without getting bogged down on details.

**Comment by pliablepixels** [comment]
Its not a priority. But if you did understand the ask and put in a PR that did something else, please put in a note about the deviation so both of us can save time.

**Comment by knight-of-ni** [comment]
Will do.

**Pull request merged**
