### PR TITLE
Dlib integration

### PR DESCRIPTION
**Pull request by web2wire**
Includes dlib base build (not superbuild) and basic integration with face detection (only) functionality.

### CODE REVIEW

**Comment by knight-of-ni** [comment]
When we add a library requirement to cmake, we need to tell Travis about it too.
Try to add the libdlib-dev package to this file here:
https://github.com/ozonesecurity/ozonebase/blob/master/.travis.yml#L39

As long as this pull request remains open, you can continue to push commits to your dlib-integration branch and they will magically show up here.

**Comment by web2wire** [comment]
Dlib is not a package as such, it's a submodule that has to be built from scratch like ffmpeg and openh264. I can't see openh264 in the travis.yml file as all and ffmpeg only gets a single reference so I'm not sure what I need to add.

**Comment by knight-of-ni** [comment]
Building external projects from source needs to be part of the superbuild. The "normal" build is not set up to do that. That's why the superbuild was created... to handle exactly what you are trying to do.

**Comment by knight-of-ni** [comment]
Note that I can do the work to make this change if you want.

**Comment by pliablepixels** [comment]
@knnniggett yes please

**Comment by knight-of-ni** [comment]
Worked through several issues with this one. Finally got it working.

**Pull request merged**
