### PR TITLE
initial commit for cmake superbuild

### PR DESCRIPTION
**Pull request by knight-of-ni**
I've got this working, but I still need to hammer out some remaining issues before we merge this.

As you can see, this places a CMakeLists.txt file into the root project folder.
The cmake superbuild process makes it easy to add additional projects to the build (e.g. perhaps client framework), and it leaves the CMakeLists.txt file under the server subfolder in a state that can be run normally, without the superbuild.

### CODE REVIEW

**Comment by pliablepixels** [comment]
@knnniggett how do I enable a debug build of the libraries? I tried `cmake -DCMAKE_BUILD_TYPE=Debug
` but that doesn't work

**Comment by knight-of-ni** [comment]
If you are trying to test this pr, the superbuild, it is not ready yet.

Check the contents of the CMakeCache.txt to verify the value of CMAKE_BUILD_TYPE.
Recall you have to delete the cache file before attemtping another build. Otherwsie it won't pick up the new settings.

**Comment by knight-of-ni** [comment]
One of the issues I am hammering out is how the header files and libraries are "found" during the superbuild process. Using the same find_library and find_path methods was convenient because the code was largely copy and paste. I merely had to add or change the paths to the location of the freshly built ffmpeg libraries. I neglected to get into the details about this in my first post because I did not anticipate anyone besides me attempting to build and test this branch until I signalled it was ready. For the moment, I'm simply using this as cloud storage for portability and to visually track my own progress. Feel free to look around and ask questions, but I still need to make some changes to if before I'd call it ready for someone else to try it.

If your debug question was in fact related to this pr, and not the master branch, then it would make sense that the debug flag did not make it into the ozonebase project. A superbuild treats each project as an externalproject, even though it is on the same filesystem. Consequently, one has to manually enumerate all the possible parameters one might anticipate being sent to either ffmpeg of ozonebase. I did look into this and there is no way to tell cmake to just "pass all of your arguments into the next project" so you have to do it like so:
https://github.com/knnniggett/ozonebase/blob/cmakesuperbuild/CMakeLists.txt#L48

Yeah, that kind of sucks. Fortunately, I don't see this project turning into a monster with a ton of parameters.

**Comment by knight-of-ni** [comment]
@pliablepixels I am now reasonably confident this will build outside of my own test environment. Can you give is a shot? The debug flag should work.

One thing I have not done is try to run any of the executables. I have not had the time to learn how to properly call them. Let me know if you can run them successfully.... both from the buildroot staging folder and after you "make install" them onto the filesystem.

**Comment by pliablepixels** [comment]
@knnniggett results of my test (ubuntu 15.04)

```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON  -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_C_COMPILER=/usr/bin/gcc

make
```

This went ahead and built ffmpeg, but failed in the last step. Logs after ffpmeg success below: `build root` only has ffmpeg includes/libs/bins. `ozonebase-build` is empty - where it complains of no Makefile

```
make[3]: Leaving directory '/home/pp/ozonebase/ffmpeg-prefix/src/ffmpeg-build'
cd /home/pp/ozonebase/ffmpeg-prefix/src/ffmpeg-build && /usr/bin/cmake -E touch /home/pp/ozonebase/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-install
/usr/bin/cmake -E cmake_progress_report /home/pp/ozonebase/CMakeFiles 1
[ 25%] Completed 'ffmpeg'
/usr/bin/cmake -E make_directory /home/pp/ozonebase/CMakeFiles
/usr/bin/cmake -E touch /home/pp/ozonebase/CMakeFiles/ffmpeg-complete
/usr/bin/cmake -E touch /home/pp/ozonebase/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-done
make[2]: Leaving directory '/home/pp/ozonebase'
/usr/bin/cmake -E cmake_progress_report /home/pp/ozonebase/CMakeFiles  1 2 3 4 5 6 7 8
[ 50%] Built target ffmpeg
make -f CMakeFiles/ozonebase.dir/build.make CMakeFiles/ozonebase.dir/depend
make[2]: Entering directory '/home/pp/ozonebase'
cd /home/pp/ozonebase && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/pp/ozonebase /home/pp/ozonebase /home/pp/ozonebase /home/pp/ozonebase /home/pp/ozonebase/CMakeFiles/ozonebase.dir/DependInfo.cmake --color=
Scanning dependencies of target ozonebase
make[2]: Leaving directory '/home/pp/ozonebase'
make -f CMakeFiles/ozonebase.dir/build.make CMakeFiles/ozonebase.dir/build
make[2]: Entering directory '/home/pp/ozonebase'
/usr/bin/cmake -E cmake_progress_report /home/pp/ozonebase/CMakeFiles 11
[ 56%] Creating directories for 'ozonebase'
/usr/bin/cmake -E make_directory /home/pp/ozonebase/server
/usr/bin/cmake -E make_directory /home/pp/ozonebase/ozonebase-prefix/src/ozonebase-build
/usr/bin/cmake -E make_directory /home/pp/ozonebase/ozonebase-prefix
/usr/bin/cmake -E make_directory /home/pp/ozonebase/ozonebase-prefix/tmp
/usr/bin/cmake -E make_directory /home/pp/ozonebase/ozonebase-prefix/src/ozonebase-stamp
/usr/bin/cmake -E make_directory /home/pp/ozonebase/ozonebase-prefix/src
/usr/bin/cmake -E touch /home/pp/ozonebase/ozonebase-prefix/src/ozonebase-stamp/ozonebase-mkdir
/usr/bin/cmake -E cmake_progress_report /home/pp/ozonebase/CMakeFiles 12
[ 62%] No download step for 'ozonebase'
cd /home/pp/ozonebase/ozonebase-prefix/src && /usr/bin/cmake -E touch /home/pp/ozonebase/ozonebase-prefix/src/ozonebase-stamp/ozonebase-download
/usr/bin/cmake -E cmake_progress_report /home/pp/ozonebase/CMakeFiles 14
[ 68%] No patch step for 'ozonebase'
/usr/bin/cmake -E touch /home/pp/ozonebase/ozonebase-prefix/src/ozonebase-stamp/ozonebase-patch
/usr/bin/cmake -E cmake_progress_report /home/pp/ozonebase/CMakeFiles 13
[ 75%] No update step for 'ozonebase'
cd /home/pp/ozonebase/server && /usr/bin/cmake -E touch /home/pp/ozonebase/ozonebase-prefix/src/ozonebase-stamp/ozonebase-update
/usr/bin/cmake -E cmake_progress_report /home/pp/ozonebase/CMakeFiles 15
[ 81%] Performing configure step for 'ozonebase'
cd /home/pp/ozonebase/ozonebase-prefix/src/ozonebase-build && /usr/bin/cmake -DOZ_SUPERBUILD=ON -DFFMPEG_LIBDIR=/home/pp/ozonebase/buildroot/usr/local/lib -DFFMPEG_INCLUDEDIR=/home/pp/ozonebase/buildroot/usr/local/include -DCMAKE_INSTALL_PREFIX=/home/pp/ozonebase/buildroot//usr/local -DCMAKE_BUILD_TYPE=Debug -DOZ_EXAMPLES= "-GUnix Makefiles" /home/pp/ozonebase/server
-- Checking whether system has ANSI C header files
-- ANSI C header files - found
-- oZonebase Superbuild detected.
-- Looking for libavfilter/avfilter.h
-- Looking for libavfilter/avfilter.h - found
-- Looking for libswresample/swresample.h
-- Looking for libswresample/swresample.h - found
-- Optional libraries found: zlib
-- Optional libraries not found:
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pp/ozonebase/server
cd /home/pp/ozonebase/ozonebase-prefix/src/ozonebase-build && /usr/bin/cmake -E touch /home/pp/ozonebase/ozonebase-prefix/src/ozonebase-stamp/ozonebase-configure
/usr/bin/cmake -E cmake_progress_report /home/pp/ozonebase/CMakeFiles 16
[ 87%] Performing build step for 'ozonebase'
cd /home/pp/ozonebase/ozonebase-prefix/src/ozonebase-build && make
make[3]: Entering directory '/home/pp/ozonebase/ozonebase-prefix/src/ozonebase-build'
make[3]: *** No targets specified and no makefile found.  Stop.
make[3]: Leaving directory '/home/pp/ozonebase/ozonebase-prefix/src/ozonebase-build'
CMakeFiles/ozonebase.dir/build.make:108: recipe for target 'ozonebase-prefix/src/ozonebase-stamp/ozonebase-build' failed
make[2]: *** [ozonebase-prefix/src/ozonebase-stamp/ozonebase-build] Error 2
make[2]: Leaving directory '/home/pp/ozonebase'
CMakeFiles/Makefile2:98: recipe for target 'CMakeFiles/ozonebase.dir/all' failed
make[1]: *** [CMakeFiles/ozonebase.dir/all] Error 2
make[1]: Leaving directory '/home/pp/ozonebase'
Makefile:110: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by knight-of-ni** [comment]
Your build output is very short. Too short. I can tell that means cmake ran with cached settings.
Try deleting: cmake-prefix folder, CMakeCache.txt, run make clean, and then call cmake without any flags. Run make and paste those results. You will notice that you will get much more output during the configuration stage.

You can leave the ffmpeg-prefix folder.

Recall that I have to manually enumerate any cmake flags we want to pass into the ozonebase project so unless I've told you the flag can be passed through, assume that it cannot. You should not have to set the compiler.

**Comment by pliablepixels** [comment]
No, it did not run with cache . I deleted the cache. I posted just the part after ffmpeg - I'll post more details   in the next round. I had to specify compilers because I was getting errors saying "A C compiler has been chosen for C++". I'll redo it.

**Comment by knight-of-ni** [comment]
When the superbuild calls ozonebase as an external project, it caches the project under {projectname}-prefix so unless you deleted that folder prior to attempting to build again, you were running with cached settings.  I've seen similar output during my testing, and after deleting the prefix folder and starting over, the problem did not return.

**Comment by knight-of-ni** [comment]
I just successfully built the project on my laptop, running Ubuntu 16.04. Previously, I had been testing on CentOS 7.

**Comment by pliablepixels** [comment]
works for me. examples run fine inside build_root. I've messed something up in my system - unless I specify a c compiler, it tries to pick up g++ (and I don't have CC set). Anyway, thats not due to your CMake script because I have the same problem building ZM. 

Validated that the examples link to the right libraries as well via `ldd`

However, I don't think dependencies are set up correctly - I made a change to `server/src/examples/starter_example.cpp` and did a `make` and it did not pick up the change.

(My cmake was `cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON  -DCMAKE_C_COMPILER=/usr/bin/gcc -DOZ_EXAMPLES=ON)
`

That being said:
a) The cmake route (non super build)  we have in master is good for now in terms of priority (vs. diving into the code), so we can return to this when you have free time 
b) I'd like to wait for @web2wire to give this a try - its quite different in terms of build_root, _prefix etc
c) I want to make absolutely sure when I switch branches/etc it doesn't re-build ffmpeg (which it probably won't, unless the switched to branch has something that changes any of the cmake files/deps, just want to try it myself)

**Comment by knight-of-ni** [comment]
> However, I don't think dependencies are set up correctly - I made a change to server/src/examples/starter_example.cpp and did a make and it did not pick up the change.

Um, it's a feature not a bug? You are using the superbuild in a way it was not intended for, but I'll get into that below. The goal behind the superbuild is to get the recommended version of ffmpeg, along with one copy of onzonebase, installed onto your filesystem so that it can be run or tested against other apps. It was not intended to be run over and over again like you would during normal development. That is what the normal cmake build is for.

The superbuild is not picking up changes because it caches the files into a folder called {project}-prefix. As mentioned twice previously, you have to delete the ozonebase-prefix folder before running the build again, if you want (any) changes to be picked up.

It is possible there might be a way to change the behavior of cmake and the way it treats externalprojects.
Try commenting the "UPDATE_COMMAND" line out and see if that gets what you want:
https://github.com/knnniggett/ozonebase/blob/cmakesuperbuild/CMakeLists.txt#L52

Do this only for ozonebase and NOT for the ffempg externalproject.

That might do it, but I don't think we need to spend a lot of time looking into this as I will explain below.

> a) The cmake route (non super build) we have in master is good for now in terms of priority (vs. diving into the code), so we can return to this when you have free time

The superbuild is so far, working as intended. I don't have any plans to make changes to it at the moment. I do want to merge this pr before we merge any future cmake changes (no plans yet), in order to avoid merge conflicts.

> b) I'd like to wait for @web2wire to give this a try - its quite different in terms of build_root, _prefix etc

That's fine, but I'm not sure what you mean by different. The end result of "make install" is exactly the same as the normal cmake build. The buildroot is just an arbitrary staging folder. One does not even need to know of its existence. The prefix is exactly the same as the normal build. To put it another way, one does not need to know what runs under the hood.

> c) I want to make absolutely sure when I switch branches/etc it doesn't re-build ffmpeg (which it probably won't, unless the switched to branch has something that changes any of the cmake files/deps, just want to try it myself)

It won't, but running builds inside your git folder is dangerous. You should not be running any build inside a git folder you push commits from. Copy the files into a new working folder then build from there. When working in your local git repo, the extra files from the build are bound to get inadvertently propagated up to our github repo sooner or later.

---

Let me summarize how the superbuild is intended to work:

Copy the project files into a new folder under your home folder

First superbuild run, from the root of the project, call:
cmake .
make
sudo make install 

If you need to build again with a different cmake flag, change the source code, or change anything at all, and _you really want to do this via the superbuild_, then do this from the root of the project folder:
make clean
rm CMakeCache.txt
rm -rf ozonebase-prefix
cmake .
make 
sudo make install

NOTE: If you have already run the superbuild once and ffmpeg is successfully installed onto your filesystem, then you no longer need to run the superbuild. Build times will be much faster if you switch to the normal cmake build under the server subfolder when you are doing normal development.

cd server
cmake .
make 
sudo make install

After ffmpeg is installed, this is the recommended way to build the ozonebase project again.
Since both the superbuild and the normal cmake build have the same installation targets, the latter build will overwrite the previous. This is by design.

So hopefully I have conveyed properly that, once you've got ffmpeg installed on your system, you no longer need the superbuild. It served its purpose. Switch to using a normal cmake build during your normal development.

**Comment by knight-of-ni** [comment]
Commit f0e1b36 adds openh264 as a submodule, tagged at v1.5.1.
This has been added to the superbuild and ffmpeg will successfully build against it.
Tested successfully on CentOS 7 and Ubuntu 16.04

**Pull request merged**
